version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: zeta_db
      POSTGRES_USER: zeta_user
      POSTGRES_PASSWORD: zeta_pass
