# Generated by Django 5.2.4 on 2025-07-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_atletas/'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='categoria',
            field=models.CharField(choices=[('mens_classic', 'Masculino Clássico-RAW'), ('womens_classic', 'Feminino Clássico-RAW')], max_length=30),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='peso',
            field=models.CharField(max_length=10),
        ),
    ]
