# Generated by Django 5.2.4 on 2025-07-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_conquista_atleta_conquista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='conquista',
        ),
        migrations.AddField(
            model_name='atleta',
            name='conquista_destaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destaques', to='pagina.conquista'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='conquistas',
            field=models.ManyToManyField(blank=True, to='pagina.conquista'),
        ),
    ]
